name: Update LeetCode Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Update LeetCode stats
        run: |
          curl -X GET "https://leetcode-stats-api.herokuapp.com/Jahnavi BS" -o leetcode.json
          python update_readme.py
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Update LeetCode stats'
          git push
